name: Build and Release Compiler

on:
  push:
    tags:
      - 'v*' # Trigger on tags starting with v

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: # If you want Mac make a PR
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSVC (Windows)
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Bootstrap nob build system (Windows)
      if: matrix.os == 'windows-latest'
      run: cl.exe /Fe:nob.exe nob.c

    - name: Bootstrap nob build system (Linux)
      if: matrix.os != 'windows-latest'
      run: gcc nob.c -o nob

    - name: Build dwoc.exe (Windows)
      if: matrix.os == 'windows-latest'
      run: .\nob.exe

    - name: Build dwoc (Linux)
      if: matrix.os != 'windows-latest'
      run: ./nob

    - name: Upload dwoc executable
      uses: actions/upload-artifact@v4
      with:
        name: dwoc-${{ matrix.os }}
        path: |
          ./build/dwoc
          ./build/dwoc.exe # This line will be ignored on non-windows platforms

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create GitHub release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload artifacts
      id: upload_artifact
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        prelease: true
        generate_release_notes: true
        files: |
          artifacts/dwoc-*
          README
